spring.application.name: spring-boot-service

server:
  port: 8083

management:
  server:
    port: 8084

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: docker
cassandra.contact-points: host.docker.internal
cassandra.keyspace: betterbotz
cassandra.local-datacenter: dc1
cassandra.port: 9042
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
        sources:
          namespace: spring-boot-service
      reload:
        enabled: true
        mode: event
kubernetes.trust.certificates: true
