server.port: 8080
management.server.port: 8085
spring.application.name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
      reload:
        enabled: true
        mode: event
        strategy: refresh
kubernetes.trust.certificates: true
management.endpoint.restart.enabled: true
